/* Filename: places_client.c */
/* Authors: Christopher Fong, Raydi Tjuandi, Gavin Limchayseng */
/* Date: 10/17/20 */
/* Revised: 10/25/20 */


/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"
#include <iostream>
#include <string>

using namespace std;

void
places_prog_1(char *host, char* city, char* state)
{
	CLIENT *clnt;
	places_ret *result_1;
	struct specified_city_state places_query_1_arg;
	places_query_1_arg.name = city;
	places_query_1_arg.state = state;
	places_query_1_arg.host = host;

#ifndef	DEBUG
	clnt = clnt_create (host, PLACES_PROG, PLACES_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = places_query_1(&places_query_1_arg, clnt);
	if (result_1 == (places_ret *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	//Prints the Error or the list of airports
	if(result_1 -> err == 0) {
		pAirportList* temp = result_1->places_ret_u.pAL;
		while(temp != nullptr){
			std::cout << "Code: " << temp->ap.code << ", ";
			std::cout << "Name: " << temp->ap.name << ", ";
			std::cout << "Distance in Miles: " << temp->ap.distance << endl;
			temp = temp->next;
		}
	} else {
		std::cout << result_1->places_ret_u.error_msg << std::endl;
	}

	return;
}


int
main (int argc, char *argv[])
{
	char *host;
	char *city;
	char *state;

	if (argc < 4) {
		printf ("usage: %s <server_host> <City> <State>\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	city = argv[2];
	state = argv[3];

	places_prog_1 (host, city, state);
	exit (0);
}
