/* Filename: places_xdr.c */
/* Authors: Christopher Fong, Raydi Tjuandi, Gavin Limchayseng */
/* Date: 10/17/20 */
/* Revised: 10/25/20 */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "places.h"

bool_t
xdr_pAirportList (XDR *xdrs, pAirportList *objp)
{
	register int32_t *buf;

	 if (!xdr_pAirport (xdrs, &objp->ap))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (pAirportList), (xdrproc_t) xdr_pAirportList))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pLocation (XDR *xdrs, pLocation *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->latitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->longitude))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_specified_city_state (XDR *xdrs, specified_city_state *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, MAX_NAME))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->state, STATE_MAX))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->host, MAX_NAME))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pAirport (XDR *xdrs, pAirport *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->code, CODE_MAX))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, MAX_NAME))
		 return FALSE;
	 if (!xdr_pLocation (xdrs, &objp->loc))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->distance))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_places_ret (XDR *xdrs, places_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_pointer (xdrs, (char **)&objp->places_ret_u.pAL, sizeof (pAirportList), (xdrproc_t) xdr_pAirportList))
			 return FALSE;
		break;
	default:
		 if (!xdr_string (xdrs, &objp->places_ret_u.error_msg, ERR_MAX))
			 return FALSE;
		break;
	}
	return TRUE;
}
