/* Filename: places.h */
/* Authors: Christopher Fong, Raydi Tjuandi, Gavin Limchayseng */
/* Date: 10/17/20 */
/* Revised: 10/25/20 */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_NAME 64
#define STATE_MAX 3
#define CODE_MAX 4
#define ERR_MAX 256

struct pLocation {
	double latitude;
	double longitude;
};
typedef struct pLocation pLocation;

struct pAirport {
	char *code;
	char *name;
	pLocation loc;
	double distance;
};
typedef struct pAirport pAirport;

struct pAirportList {
	pAirport ap;
	struct pAirportList *next;
};
typedef struct pAirportList pAirportList;

struct specified_city_state {
	char *name;
	char *state;
	char *host;
};
typedef struct specified_city_state specified_city_state;

struct places_ret {
	int err;
	union {
		pAirportList *pAL;
		char *error_msg;
	} places_ret_u;
};
typedef struct places_ret places_ret;

#define PLACES_PROG 0x82838281
#define PLACES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PLACES_QUERY 1
extern  places_ret * places_query_1(specified_city_state *, CLIENT *);
extern  places_ret * places_query_1_svc(specified_city_state *, struct svc_req *);
extern int places_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PLACES_QUERY 1
extern  places_ret * places_query_1();
extern  places_ret * places_query_1_svc();
extern int places_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_pAirportList (XDR *, pAirportList*);
extern  bool_t xdr_pLocation (XDR *, pLocation*);
extern  bool_t xdr_specified_city_state (XDR *, specified_city_state*);
extern  bool_t xdr_pAirport (XDR *, pAirport*);
extern  bool_t xdr_places_ret (XDR *, places_ret*);

#else /* K&R C */
extern bool_t xdr_pAirportList ();
extern bool_t xdr_pLocation ();
extern bool_t xdr_specified_city_state ();
extern bool_t xdr_pAirport ();
extern bool_t xdr_places_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
